export const SET_MOVIE_LIST = 'SET_MOVIE_LIST';
export const SET_SIMILAR_MOVIE = 'SET_SIMILAR_MOVIE';
export const SET_UPCOMING_MOVIE = 'SET_UPCOMING_MOVIE';
export const SET_FETCH_LOADING = 'SET_FETCH_LOADING';
export const SET_MOVIE_TRAILER = 'SET_MOVIE_TRAILER';